// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDACUnHdMRFQQOhy6l50Rm_3cgtSWECPAU',
    appId: '1:725886665003:web:ab68e611e677f53835056e',
    messagingSenderId: '725886665003',
    projectId: 'habit-tracking-b4039',
    authDomain: 'habit-tracking-b4039.firebaseapp.com',
    storageBucket: 'habit-tracking-b4039.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4J0h6iFx2ww0N7rKJTHLyH3eUJO9_M8c',
    appId: '1:725886665003:android:c65476ac0845029235056e',
    messagingSenderId: '725886665003',
    projectId: 'habit-tracking-b4039',
    storageBucket: 'habit-tracking-b4039.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwWWjZD7cMTgkf5EMFhHj3oXJobI0DTTk',
    appId: '1:725886665003:ios:fa2f4c8f4946fe5235056e',
    messagingSenderId: '725886665003',
    projectId: 'habit-tracking-b4039',
    storageBucket: 'habit-tracking-b4039.firebasestorage.app',
    iosBundleId: 'com.example.habitTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwWWjZD7cMTgkf5EMFhHj3oXJobI0DTTk',
    appId: '1:725886665003:ios:fa2f4c8f4946fe5235056e',
    messagingSenderId: '725886665003',
    projectId: 'habit-tracking-b4039',
    storageBucket: 'habit-tracking-b4039.firebasestorage.app',
    iosBundleId: 'com.example.habitTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDACUnHdMRFQQOhy6l50Rm_3cgtSWECPAU',
    appId: '1:725886665003:web:e0707d9e4fd19a3c35056e',
    messagingSenderId: '725886665003',
    projectId: 'habit-tracking-b4039',
    authDomain: 'habit-tracking-b4039.firebaseapp.com',
    storageBucket: 'habit-tracking-b4039.firebasestorage.app',
  );
}
