// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM9CCWNBApwnJ2w36HX9hePzoYn6iixXA',
    appId: '1:107390424918:web:0f50473865aba1d6a828f7',
    messagingSenderId: '107390424918',
    projectId: 'habittracking-ca4d5',
    authDomain: 'habittracking-ca4d5.firebaseapp.com',
    storageBucket: 'habittracking-ca4d5.appspot.com',
    measurementId: 'G-XVBY42NL11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD784_R2ynbAKu7NWgMyIW6e0SZ59Vlmc8',
    appId: '1:107390424918:android:b451c8f33f58b92ba828f7',
    messagingSenderId: '107390424918',
    projectId: 'habittracking-ca4d5',
    storageBucket: 'habittracking-ca4d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlAOJ5ZsiurnwomRw37y8uGT4WShGdDHM',
    appId: '1:107390424918:ios:f3ee4341de545b22a828f7',
    messagingSenderId: '107390424918',
    projectId: 'habittracking-ca4d5',
    storageBucket: 'habittracking-ca4d5.appspot.com',
    iosBundleId: 'com.example.firebaseSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlAOJ5ZsiurnwomRw37y8uGT4WShGdDHM',
    appId: '1:107390424918:ios:f3ee4341de545b22a828f7',
    messagingSenderId: '107390424918',
    projectId: 'habittracking-ca4d5',
    storageBucket: 'habittracking-ca4d5.appspot.com',
    iosBundleId: 'com.example.firebaseSignin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM9CCWNBApwnJ2w36HX9hePzoYn6iixXA',
    appId: '1:107390424918:web:808f7e450ae08b93a828f7',
    messagingSenderId: '107390424918',
    projectId: 'habittracking-ca4d5',
    authDomain: 'habittracking-ca4d5.firebaseapp.com',
    storageBucket: 'habittracking-ca4d5.appspot.com',
    measurementId: 'G-8MXZXBTKW8',
  );

}